spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wayd_user
    username: postgres
    password: postgres
  application:
    name: wayd-user


server:
  port: 8081
  servlet:
    context-path: /user-service-api


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
    enabled: false

keycloak:
  enabled: true
  auth-server-url: http://localhost:8484/auth
  realm: WAYD
  resource: user-service
  credentials:
    secret: w2I3mMBLDlEZXEyKpwMq13i3adL7fz6j

jwt:
  secret: very-secret-key
  prefix: Bearer

wayd:
  kafka:
    address: localhost:9092
    groupId: validator
    producer:
      id: validator-producer
  confirmation-code:
    duration: 15
    length: 6