spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wayd_user
    username: postgres
    password: postgres


server:
  port: 8081
#  servlet:
#    context-path: /user-service-api

jwt:
  secret: very-secret-key
